/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package l03;

import pt.ist.ap.labs.Shell;

import java.io.IOException;

public class App {

	public static void main(String[] args) {
		Shell shell = new Shell();

		try {
			shell.repl();
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
}
